spring.application.name=spring_security_Project

#DB configuration
# Connection URL (replace 'my_spring_app' with your database name)
spring.datasource.url=jdbc:postgresql://localhost:5432/hospital_management_security
spring.datasource.username=aman
spring.datasource.password=spring
# JPA / Hibernate Configurations
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true




server.servlet.context-path=/api/v1
logging.level.org.springframework.web=DEBUG
