spring.application.name=spring_security_Project

#DB configuration
# Connection URL (replace 'my_spring_app' with your database name)
spring.datasource.url=jdbc:postgresql://localhost:5432/hospital_management_security
spring.datasource.username=aman
spring.datasource.password=spring
# JPA / Hibernate Configurations
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


server.servlet.context-path=/api/v1
logging.level.org.springframework.web=DEBUG


#security configuration
# Following are the default username and password for Spring Security. You can change them as per your requirement.
# This will be stored in server and will be used for basic authentication.

#spring.security.user.name=aman
#spring.security.user.password=password


#Adding jwt scret key

jwt.secretKey=cnjkasnkaslnxajbiankjcnakj128y9ncksnd732y9eihkjsnckjsanstugixkasjbbjakds

